version: "3.7"

services:

  jaeger:
    hostname: jaeger
    image: jaegertracing/all-in-one:1.31
    networks:
      sync_nw:
    ports:
      - "16686:16686"
      - "14268:14268"
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: 250M

  zipkin:
    hostname: zipkin
    image: openzipkin/zipkin:2.23.15
    networks:
      sync_nw:
    ports:
      - "9411:9411"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 800M
#  registry:
#    image: sync-registry
#    ports:
#      - "9999:9999"
#    networks:
#      sync_nw:
#  ubuntu-shell:
#    image: ubuntu-shell
#    container_name: ubuntu-shell
#    hostname: ubuntu-shell
#    # build:
#    #   context: .
#    #   dockerfile: ubuntu.Dockerfile
#    ports:
#      - "9000:9000"
#    volumes:
#      - .:/syncEngine
#    stdin_open: true
#    tty: true
#    command: "zsh"
#    #sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

volumes:
  ubuntu-shell-volume:
    external: true

networks:
  sync_nw:
    driver:
      bridge
