

version: "3.7"

services:

  jaeger:
    container_name: jaeger
    hostname: jaeger
    image: jaegertracing/all-in-one:1.31
    ports:
      - "16686:16686"
      - "14268:14268"
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: 250M